FROM golang:1.14-alpine AS builder

RUN apk add --no-cache --quiet ca-certificates git make ncurses

WORKDIR /src
ADD . .

RUN make build-ssm-secrets-webhook

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /src/build/ssm-secrets-webhook /

# Avoid running as root or named user, to satisfy PSPs
USER 65534

ENTRYPOINT ["/ssm-secrets-webhook"]
